MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/l/ls/pre_weight/jx_vit_base_p16_224-80ecf9dd.pth'
  SOURCE_PATH: '/home/l/ls/pre_weight/transformer_m2d_120_eras.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('1')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [14, 14]

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('market1501')
  ROOT_DIR: ('/home/l/ls/reid_data')
  TARGET_NAMES: ('msmt17_new')
  IS_NEW: True

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  CAMERA_NUM: 15

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 400
  BASE_LR: 0.004
  CITRA_IMS_PER_BATCH: 64
  IMS_PER_BATCH: 128
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 100
  LOG_PERIOD: 50
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  ITERS: 50
  THRES: 0.118
  STATR_EPOCH: 0
  a: 1.8
  b: 1.4

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: '../logs/0321_market_vit_base/transformer_120.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: '../LRIMV_log/LRRMII_V1_M2MSMT17'


